/**
 * Ikon UI terpusat (react-icons). Komponen memakai alias semantik ini
 * alih-alih emoji. Emoji yang berasal dari DATA (mis. node.emoji, role emoji)
 * tetap dipakai apa adanya — ini hanya untuk ikon UI.
 */
export {
  FiHome as HomeIcon,
  FiMap as MapIcon,
  FiMessageSquare as ChatIcon,
  FiMessageCircle as DmIcon,
  FiUsers as UsersIcon,
  FiUser as UserIcon,
  FiHeadphones as HeadphonesIcon,
  FiMapPin as PinIcon,
  FiLock as LockIcon,
  FiCheck as CheckIcon,
  FiX as CloseIcon,
  FiStar as StarIcon,
  FiHeart as HeartIcon,
  FiArrowLeft as ArrowLeftIcon,
  FiArrowRight as ArrowRightIcon,
  FiArrowUpRight as ExternalIcon,
  FiPlay as PlayIcon,
  FiPause as PauseIcon,
  FiSkipForward as NextIcon,
  FiSkipBack as PrevIcon,
  FiShuffle as ShuffleIcon,
  FiUpload as UploadIcon,
  FiTrash2 as TrashIcon,
  FiVolume2 as VolumeIcon,
  FiRefreshCw as RefreshIcon,
  FiSearch as SearchIcon,
  FiSmile as SmileIcon,
  FiBookOpen as BookIcon,
  FiTarget as TargetIcon,
  FiPaperclip as AttachIcon,
  FiFile as FileIcon,
  FiImage as ImageIcon,
  FiPackage as PackageIcon,
  FiFileText as DocIcon,
  FiEdit2 as EditIcon,
  FiBarChart2 as ChartIcon,
  FiCompass as CompassIcon,
  FiZap as SparkleIcon,
  FiAlertTriangle as AlertIcon,
  FiCalendar as CalendarIcon,
  FiClock as ClockIcon,
  FiMail as MailIcon,
  FiLink as LinkIcon,
  FiMicOff as MicOffIcon,
  FiMic as MicIcon,
  FiMusic as MusicIcon,
  FiCode as CodeIcon,
  FiCheckCircle as CheckCircleIcon,
  FiXCircle as XCircleIcon,
  FiPlus as PlusIcon,
  FiLayers as SkillIcon,
  FiCircle as DotIcon,
  FiActivity as ActivityIcon,
  FiPhone as PhoneIcon,
  FiPhoneOff as PhoneOffIcon,
  FiVideo as VideoIcon,
  FiVideoOff as VideoOffIcon,
  FiLogOut as LogoutIcon,
  FiBriefcase as BriefcaseIcon,
  FiAward as AwardIcon,
  FiSun as SunIcon,
  FiMoon as MoonIcon,
} from "react-icons/fi";
export {
  FaGraduationCap as GradIcon,
  FaCodeFork as ForkIcon,
  FaFire as FireIcon,
  FaMask as MaskIcon,
  FaPuzzlePiece as BrandIcon,
  FaBrain as QuizIcon,
  FaGithub as GithubIcon,
} from "react-icons/fa6";
export { LuPartyPopper as PartyIcon } from "react-icons/lu";
